// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cmcookies.Models;

#nullable disable

namespace cmcookies.Migrations
{
    [DbContext(typeof(CmcDBContext))]
    [Migration("20251130221226_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("cmcookies.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("CookieCode")
                        .HasColumnType("int")
                        .HasColumnName("cookie_code");

                    b.Property<DateTime?>("ProducedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("produced_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("QtyMade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("qty_made")
                        .HasDefaultValueSql("'20'");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_cost");

                    b.HasKey("BatchId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CookieCode" }, "fk_batches_cookie_code");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("cmcookies.Models.Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("billing_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillingId"));

                    b.Property<string>("BillingType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('cash','card')")
                        .HasColumnName("billing_type")
                        .HasDefaultValueSql("'cash'");

                    b.HasKey("BillingId")
                        .HasName("PRIMARY");

                    b.ToTable("billing");
                });

            modelBuilder.Entity("cmcookies.Models.Cookie", b =>
                {
                    b.Property<int>("CookieCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cookie_code");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CookieCode"));

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('normal','seasonal')")
                        .HasColumnName("category")
                        .HasDefaultValueSql("'normal'");

                    b.Property<string>("CookieName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cookie_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_path");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stock")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("CookieCode")
                        .HasName("PRIMARY");

                    b.ToTable("cookies");
                });

            modelBuilder.Entity("cmcookies.Models.CookieMaterial", b =>
                {
                    b.Property<int>("CookieMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cookie_material_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CookieMaterialId"));

                    b.Property<decimal>("ConsumptionPerBatch")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("consumption_per_batch");

                    b.Property<int>("CookieCode")
                        .HasColumnType("int")
                        .HasColumnName("cookie_code");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.HasKey("CookieMaterialId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CookieCode" }, "fk_cookiematerials_cookie_code");

                    b.HasIndex(new[] { "MaterialId" }, "fk_cookiematerials_material_id");

                    b.ToTable("cookie_materials");
                });

            modelBuilder.Entity("cmcookies.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("phone_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CustomerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PhoneId" }, "fk_customer_id");

                    b.HasIndex(new[] { "UserId" }, "fk_customers_user_id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("cmcookies.Models.CustomerBilling", b =>
                {
                    b.Property<int>("CustomerBillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_billing_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerBillingId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BillingId")
                        .HasColumnType("int")
                        .HasColumnName("billing_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    b.HasKey("CustomerBillingId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BillingId" }, "fk_custbill_billing_id");

                    b.HasIndex(new[] { "CustomerId" }, "fk_custbill_customer_id");

                    b.HasIndex(new[] { "OrderDetailId" }, "fk_custbill_order_detail_id");

                    b.ToTable("customer_billings");
                });

            modelBuilder.Entity("cmcookies.Models.CustomerShipping", b =>
                {
                    b.Property<int>("CustomerShippingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_shippings_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerShippingsId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    b.Property<int>("ShippingId")
                        .HasColumnType("int")
                        .HasColumnName("shipping_id");

                    b.HasKey("CustomerShippingsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "fk_custship_customer_id");

                    b.HasIndex(new[] { "OrderDetailId" }, "fk_custship_orderdetail_id");

                    b.HasIndex(new[] { "ShippingId" }, "fk_custship_shipping_id");

                    b.ToTable("customer_shippings");
                });

            modelBuilder.Entity("cmcookies.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Stock")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("stock");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_cost");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("MaterialId")
                        .HasName("PRIMARY");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("cmcookies.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Bag")
                        .HasColumnType("enum('small','medium')")
                        .HasColumnName("bag");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','on_preparation','delivered','cancelled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<bool?>("Sticker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sticker")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("OrderId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "fk_orders_customer");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("cmcookies.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("CookieCode")
                        .HasColumnType("int")
                        .HasColumnName("cookie_code");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderDetailId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CookieCode" }, "fk_order_details_cookie_code");

                    b.HasIndex(new[] { "OrderId" }, "fk_order_details_order_id");

                    b.ToTable("order_details");
                });

            modelBuilder.Entity("cmcookies.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("phone_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PhoneId"));

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_1");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_2");

                    b.HasKey("PhoneId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Phone1" }, "phone_1")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone2" }, "phone_2")
                        .IsUnique();

                    b.ToTable("phones");
                });

            modelBuilder.Entity("cmcookies.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("role_type");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("cmcookies.Models.Shipping", b =>
                {
                    b.Property<int>("ShippingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipping_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShippingId"));

                    b.Property<string>("ShippingSite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("shipping_site");

                    b.Property<string>("ShippingType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('on campus','outside campus')")
                        .HasColumnName("shipping_type")
                        .HasDefaultValueSql("'on campus'");

                    b.HasKey("ShippingId")
                        .HasName("PRIMARY");

                    b.ToTable("shipping");
                });

            modelBuilder.Entity("cmcookies.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("enum('sale','production','material_purchase')")
                        .HasColumnName("transaction_type");

                    b.HasKey("TransactionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BatchId" }, "fk_transactions_batch");

                    b.HasIndex(new[] { "MaterialId" }, "fk_transactions_material");

                    b.HasIndex(new[] { "OrderId" }, "fk_transactions_order");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("cmcookies.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("cmcookies.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("cmcookies.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("cmcookies.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("cmcookies.Models.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cmcookies.Models.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("cmcookies.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cmcookies.Models.Batch", b =>
                {
                    b.HasOne("cmcookies.Models.Cookie", "CookieCodeNavigation")
                        .WithMany("Batches")
                        .HasForeignKey("CookieCode")
                        .IsRequired()
                        .HasConstraintName("fk_batches_cookie_code");

                    b.Navigation("CookieCodeNavigation");
                });

            modelBuilder.Entity("cmcookies.Models.CookieMaterial", b =>
                {
                    b.HasOne("cmcookies.Models.Cookie", "CookieCodeNavigation")
                        .WithMany("CookieMaterials")
                        .HasForeignKey("CookieCode")
                        .IsRequired()
                        .HasConstraintName("fk_cookiematerials_cookie_code");

                    b.HasOne("cmcookies.Models.Material", "Material")
                        .WithMany("CookieMaterials")
                        .HasForeignKey("MaterialId")
                        .IsRequired()
                        .HasConstraintName("fk_cookiematerials_material_id");

                    b.Navigation("CookieCodeNavigation");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("cmcookies.Models.Customer", b =>
                {
                    b.HasOne("cmcookies.Models.Phone", "Phone")
                        .WithMany("Customers")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("fk_customer_id");

                    b.HasOne("cmcookies.Models.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_customers_user_id");

                    b.Navigation("Phone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cmcookies.Models.CustomerBilling", b =>
                {
                    b.HasOne("cmcookies.Models.Billing", "Billing")
                        .WithMany("CustomerBillings")
                        .HasForeignKey("BillingId")
                        .IsRequired()
                        .HasConstraintName("fk_custbill_billing_id");

                    b.HasOne("cmcookies.Models.Customer", "Customer")
                        .WithMany("CustomerBillings")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_custbill_customer_id");

                    b.HasOne("cmcookies.Models.OrderDetail", "OrderDetail")
                        .WithMany("CustomerBillings")
                        .HasForeignKey("OrderDetailId")
                        .IsRequired()
                        .HasConstraintName("fk_custbill_order_detail_id");

                    b.Navigation("Billing");

                    b.Navigation("Customer");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("cmcookies.Models.CustomerShipping", b =>
                {
                    b.HasOne("cmcookies.Models.Customer", "Customer")
                        .WithMany("CustomerShippings")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_custship_customer_id");

                    b.HasOne("cmcookies.Models.OrderDetail", "OrderDetail")
                        .WithMany("CustomerShippings")
                        .HasForeignKey("OrderDetailId")
                        .IsRequired()
                        .HasConstraintName("fk_custship_orderdetail_id");

                    b.HasOne("cmcookies.Models.Shipping", "Shipping")
                        .WithMany("CustomerShippings")
                        .HasForeignKey("ShippingId")
                        .IsRequired()
                        .HasConstraintName("fk_custship_shipping_id");

                    b.Navigation("Customer");

                    b.Navigation("OrderDetail");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("cmcookies.Models.Order", b =>
                {
                    b.HasOne("cmcookies.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_orders_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("cmcookies.Models.OrderDetail", b =>
                {
                    b.HasOne("cmcookies.Models.Cookie", "CookieCodeNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CookieCode")
                        .IsRequired()
                        .HasConstraintName("fk_order_details_cookie_code");

                    b.HasOne("cmcookies.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_order_details_order_id");

                    b.Navigation("CookieCodeNavigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("cmcookies.Models.Transaction", b =>
                {
                    b.HasOne("cmcookies.Models.Batch", "Batch")
                        .WithMany("Transactions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_batch");

                    b.HasOne("cmcookies.Models.Material", "Material")
                        .WithMany("Transactions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_material");

                    b.HasOne("cmcookies.Models.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_order");

                    b.Navigation("Batch");

                    b.Navigation("Material");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("cmcookies.Models.Batch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("cmcookies.Models.Billing", b =>
                {
                    b.Navigation("CustomerBillings");
                });

            modelBuilder.Entity("cmcookies.Models.Cookie", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("CookieMaterials");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("cmcookies.Models.Customer", b =>
                {
                    b.Navigation("CustomerBillings");

                    b.Navigation("CustomerShippings");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("cmcookies.Models.Material", b =>
                {
                    b.Navigation("CookieMaterials");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("cmcookies.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("cmcookies.Models.OrderDetail", b =>
                {
                    b.Navigation("CustomerBillings");

                    b.Navigation("CustomerShippings");
                });

            modelBuilder.Entity("cmcookies.Models.Phone", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("cmcookies.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("cmcookies.Models.Shipping", b =>
                {
                    b.Navigation("CustomerShippings");
                });

            modelBuilder.Entity("cmcookies.Models.User", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
